### PR TITLE
Move dev host mappings into their own yml

### PR DESCRIPTION
**Pull request by yorickdowne**

### CODE REVIEW

**Review by pradavc — CHANGES_REQUESTED** [review]
So the idea is only modify the dev yml files, and ask people to edit de .env example accordingly, right? It might break some configs from already deployed nodes, but it makes sense. Could you resolve conflicts before merging @yorickdowne ?

**Comment by yorickdowne** [comment]
Yes the idea is that people who want access on their local host to web3signer, keymanager, and the CL and EL REST and RPC APIs respectively, would add the corresponding dev-ports.yml to their `COMPOSE_FILE`. It won't break anything for people who just run a node.

I am a little puzzled why it shows the changes it does in the diff, on my screen it claims docker-compose-lodestar-vc.yml is entirely new, when it really isn't.

**Comment by pradavc** [comment]
I think you have done a merge from main, which is re-introducing everything again instead of a rebasing. Can you do a rebasing instead?

**Comment by yorickdowne** [comment]
Merged once more. Let me try a rebase; I did that earlier and it messed things up

**Comment by yorickdowne** [comment]
git will be the death of me :sweat_smile: 

This should do it. Note the mapping for node-exporter is gone entirely. I don't see a use for it even for devs, as it only needs to be scraped by prometheus and that happens via the docker network

The prometheus mapping stays in place as it's genuinely useful to users, so they can troubleshoot scrapes that don't work

**Review by pradavc — APPROVED** [review]
lgtm, great contributions @yorickdowne , you are killing it today

**Comment by yorickdowne** [comment]
Oh actually. This will break things for people who are going out of docker for their stuff, while it's in docker. So http://HOST-IP:port would need to become http://prysm:4000 for example.

This may be worth pointing out in the announcement and in .env.default

**Pull request merged**
